#! /bin/bash
tar -xvzf -C /usr/local <(wget -qO- https://golang.google.cn/dl/go1.17.6.linux-amd64.tar.gz)

echo "
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
export GOROOT=/usr/local/go
export GOPATH=/usr/local/go/path
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
" >> /etc/profile

source /etc/profile
