#! /bin/bash
tar -xvzf <(wget -qO- https://golang.google.cn/dl/go1.17.6.linux-amd64.tar.gz) -C /usr/local
tee -a ./profile << 'EOF'
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
export GOROOT=/usr/local/go
export GOPATH=/usr/local/go/path
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
EOF

source /etc/profile
apt update -y
apt install cmark -y
exec -l $SHELL
