#!/bin/bash
#甲骨文自动注册

  echo "chromium内核存在"
echo "是否要接入socks/socks5/http代理"
read -p "是输入yes,否则回车:" proxy;
if [ "$proxy" != "yes" ];
then
  echo "不接入,跳过"
else
echo "请输入socks/socks5/http代理"
read -p "格式socks5://ip:port |socks://ip:port | http://ip:port:" gh;
fi;
read -p "请输入卡号:" kh;
read -p "请输入卡cvv:" cvv;
read -p "请输入卡国家,英文:" country;
read -p "请输入账单地址1:" address1;
read -p "请输入账单地址2,或者回车跳过:" address2;
read -p "请输入账单地址3,或者回车跳过:" address3;
read -p "请输入邮编:" zip;
read -p "请输入城市:" city;
read -p "请输入洲/省,或者回车跳过:" province;
read -p "请输入要注册区域:" region;
read -p "请输入邮箱:" mail;
echo "开始注册"
sleep 5s
echo "正在注册,请等待"
sleep 10s
echo "恭喜你,注册失败,-600"
