#!/bin/bash
red(){
    echo -e "\033[31m\033[01m$1\033[0m"
}
green(){
    echo -e "\033[32m\033[01m$1\033[0m"
}

telnet="$(command -v telnet)"
if [ "$telnet" != "" ]
then 
red "脚本仅仅测试本地端口,请勿用于非法用途"
green "telnet!存在!"
else 
red "不存在telnet,正在安装"
sys="$(cat /etc/issue)"
if [[ $(cat /etc/issue | grep -i -e "debian|ubuntu" ) != "" ]];                                                                                 
then a=yum
else a=apt
fi;
$a update -y >/dev/null 2>&1;$a install telnet >/dev/null 2>&1
telnet="$(command -v telnet)"
if [ "$telnet" != "" ]
then 
green "telnet安装成功"
else 
red "不存在telnet,安装失败!请手动安装!"
fi;
fi;



echo "直接回车默认127.0.0.1"
read -p "输入ip=" ip;
if [ -z $ip ]
then ip=127.0.0.1;
fi;
read -p "输入开始端口=" aport;
read -p "输入结束端口=" zport;
red "是否要输出开启的端口到txt?"
read -p "是输入yes否则回车=" txt;
if [ "$txt" != "yes" ];
then echo ""
else read -p "自定义txt文件名=" txt1;
fi;
if [ "$ip" = "127.0.0.1" ]
then ms=0.1
else
red "请输入自定义断开延迟,目标ip离你越近延迟可输入越低,300的ping值一般0.5足以"
read -p "自定义输入延迟=" ms;
fi;
num=0
for ((i=${aport};i<=${zport};i+=1))
do


nport=`echo ""|timeout --signal=9 $ms telnet ${ip} ${i} 2>/dev/null|grep "\^]"|wc -l`
if [ "$nport" -eq "0" ];then
echo "${ip}:${i}端口没有开启">>/dev/null
else 
if [ "$txt" = "yes" ];
then
echo "${i}" >> ${txt1}.txt
fi;
echo "${ip}:${i}端口开启"
fi;
done
