#!/bin/bash
echo '正在安装speedtest,请等待'
bash <(curl -s https://install.speedtest.net/app/cli/install.deb.sh) >/dev/null 2>&1
apt install speedtest -y >/dev/null 2>&1
echo '安装成功，开始测速'
speedtest
echo '测速完成，再次测速请执行speedtest'
