#!/bin/bash
green(){
    echo -e "\033[32m\033[01m$1\033[0m"
}
clear
green "
—————————————————————————————————————————————————————————————
               欢迎使用Linux便民工具箱
—————————————————————————————————————————————————————————————
"

[[ $(id -u) != 0 ]] && green "检测到当前环境非root用户，请先执行sudo su切换root用户执行脚本" && exit 1

green "1.一键安装docker"
green "2.一键cloudflare内网穿透"

read -p "请输入序号: " yn
 if [[ $yn == "1" ]];then
  bash <(curl -sSL 'https://cdn.jsdelivr.net/gh/mslxi/mslx/docker')
 elif [[ $yn == "2" ]];then
  bash <(curl -sSL 'https://cdn.jsdelivr.net/gh/mslxi/mslx/Tunnel')
else
   green "输入有误，脚本退出
如有需要请重新运行"
   exit 1
fi